version: "3.1"

services:
  postgres:
    image: postgres:15-alpine3.18
    container_name: cardapio-container
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cardapio
